name: Build Docker Images

on:
  push:
    branches:
      - main
    paths:
      - "docker/**"
  workflow_dispatch:

jobs:
  build-amd64-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push amd64 image
        run: |
          docker build -t ghcr.io/kiloexabyte/wails-ubuntu-amd64:latest -f docker/Dockerfile.ubuntu-amd64 .
          docker push ghcr.io/kiloexabyte/wails-ubuntu-amd64:latest

  build-arm64-image:
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push arm64 image
        run: |
          docker build -t ghcr.io/kiloexabyte/wails-ubuntu-arm64:latest -f docker/Dockerfile.ubuntu-arm64 .
          docker push ghcr.io/kiloexabyte/wails-ubuntu-arm64:latest
